[package]
name = "day-16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mry = "^0.2"
ndarray = "^0.15"

[features]
sample = []
part2 = []
