[package]
name = "day-17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mry = "^0.2"
petgraph = "0.6.4"

[features]
sample = []
part2 = []
