[package]
name = "day-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mry = "0.2"
sscanf = "0.4.1"
petgraph = "0.6.4"
num = "0.4.1"

[features]
sample = []
part2 = []